// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.dc.raft.network;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Metadta metadta = 1;</code>
   * @return Whether the metadta field is set.
   */
  boolean hasMetadta();
  /**
   * <code>.Metadta metadta = 1;</code>
   * @return The metadta.
   */
  com.dc.raft.network.Metadta getMetadta();
  /**
   * <code>.Metadta metadta = 1;</code>
   */
  com.dc.raft.network.MetadtaOrBuilder getMetadtaOrBuilder();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
