// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.dc.raft.network;

/**
 * Protobuf type {@code Payload}
 */
public final class Payload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Payload)
    PayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Payload.newBuilder() to construct.
  private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payload() {
    body_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Payload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Payload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.dc.raft.network.Metadta.Builder subBuilder = null;
            if (metadta_ != null) {
              subBuilder = metadta_.toBuilder();
            }
            metadta_ = input.readMessage(com.dc.raft.network.Metadta.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadta_);
              metadta_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {

            body_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dc.raft.network.Request.internal_static_Payload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dc.raft.network.Request.internal_static_Payload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dc.raft.network.Payload.class, com.dc.raft.network.Payload.Builder.class);
  }

  public static final int METADTA_FIELD_NUMBER = 1;
  private com.dc.raft.network.Metadta metadta_;
  /**
   * <code>.Metadta metadta = 1;</code>
   * @return Whether the metadta field is set.
   */
  @java.lang.Override
  public boolean hasMetadta() {
    return metadta_ != null;
  }
  /**
   * <code>.Metadta metadta = 1;</code>
   * @return The metadta.
   */
  @java.lang.Override
  public com.dc.raft.network.Metadta getMetadta() {
    return metadta_ == null ? com.dc.raft.network.Metadta.getDefaultInstance() : metadta_;
  }
  /**
   * <code>.Metadta metadta = 1;</code>
   */
  @java.lang.Override
  public com.dc.raft.network.MetadtaOrBuilder getMetadtaOrBuilder() {
    return getMetadta();
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metadta_ != null) {
      output.writeMessage(1, getMetadta());
    }
    if (!body_.isEmpty()) {
      output.writeBytes(2, body_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metadta_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetadta());
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, body_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dc.raft.network.Payload)) {
      return super.equals(obj);
    }
    com.dc.raft.network.Payload other = (com.dc.raft.network.Payload) obj;

    if (hasMetadta() != other.hasMetadta()) return false;
    if (hasMetadta()) {
      if (!getMetadta()
          .equals(other.getMetadta())) return false;
    }
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadta()) {
      hash = (37 * hash) + METADTA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadta().hashCode();
    }
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dc.raft.network.Payload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dc.raft.network.Payload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dc.raft.network.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dc.raft.network.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dc.raft.network.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dc.raft.network.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dc.raft.network.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dc.raft.network.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dc.raft.network.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dc.raft.network.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dc.raft.network.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dc.raft.network.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dc.raft.network.Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Payload)
      com.dc.raft.network.PayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dc.raft.network.Request.internal_static_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dc.raft.network.Request.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dc.raft.network.Payload.class, com.dc.raft.network.Payload.Builder.class);
    }

    // Construct using com.dc.raft.network.Payload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (metadtaBuilder_ == null) {
        metadta_ = null;
      } else {
        metadta_ = null;
        metadtaBuilder_ = null;
      }
      body_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dc.raft.network.Request.internal_static_Payload_descriptor;
    }

    @java.lang.Override
    public com.dc.raft.network.Payload getDefaultInstanceForType() {
      return com.dc.raft.network.Payload.getDefaultInstance();
    }

    @java.lang.Override
    public com.dc.raft.network.Payload build() {
      com.dc.raft.network.Payload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dc.raft.network.Payload buildPartial() {
      com.dc.raft.network.Payload result = new com.dc.raft.network.Payload(this);
      if (metadtaBuilder_ == null) {
        result.metadta_ = metadta_;
      } else {
        result.metadta_ = metadtaBuilder_.build();
      }
      result.body_ = body_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dc.raft.network.Payload) {
        return mergeFrom((com.dc.raft.network.Payload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dc.raft.network.Payload other) {
      if (other == com.dc.raft.network.Payload.getDefaultInstance()) return this;
      if (other.hasMetadta()) {
        mergeMetadta(other.getMetadta());
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dc.raft.network.Payload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dc.raft.network.Payload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.dc.raft.network.Metadta metadta_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dc.raft.network.Metadta, com.dc.raft.network.Metadta.Builder, com.dc.raft.network.MetadtaOrBuilder> metadtaBuilder_;
    /**
     * <code>.Metadta metadta = 1;</code>
     * @return Whether the metadta field is set.
     */
    public boolean hasMetadta() {
      return metadtaBuilder_ != null || metadta_ != null;
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     * @return The metadta.
     */
    public com.dc.raft.network.Metadta getMetadta() {
      if (metadtaBuilder_ == null) {
        return metadta_ == null ? com.dc.raft.network.Metadta.getDefaultInstance() : metadta_;
      } else {
        return metadtaBuilder_.getMessage();
      }
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    public Builder setMetadta(com.dc.raft.network.Metadta value) {
      if (metadtaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadta_ = value;
        onChanged();
      } else {
        metadtaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    public Builder setMetadta(
        com.dc.raft.network.Metadta.Builder builderForValue) {
      if (metadtaBuilder_ == null) {
        metadta_ = builderForValue.build();
        onChanged();
      } else {
        metadtaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    public Builder mergeMetadta(com.dc.raft.network.Metadta value) {
      if (metadtaBuilder_ == null) {
        if (metadta_ != null) {
          metadta_ =
            com.dc.raft.network.Metadta.newBuilder(metadta_).mergeFrom(value).buildPartial();
        } else {
          metadta_ = value;
        }
        onChanged();
      } else {
        metadtaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    public Builder clearMetadta() {
      if (metadtaBuilder_ == null) {
        metadta_ = null;
        onChanged();
      } else {
        metadta_ = null;
        metadtaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    public com.dc.raft.network.Metadta.Builder getMetadtaBuilder() {
      
      onChanged();
      return getMetadtaFieldBuilder().getBuilder();
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    public com.dc.raft.network.MetadtaOrBuilder getMetadtaOrBuilder() {
      if (metadtaBuilder_ != null) {
        return metadtaBuilder_.getMessageOrBuilder();
      } else {
        return metadta_ == null ?
            com.dc.raft.network.Metadta.getDefaultInstance() : metadta_;
      }
    }
    /**
     * <code>.Metadta metadta = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dc.raft.network.Metadta, com.dc.raft.network.Metadta.Builder, com.dc.raft.network.MetadtaOrBuilder> 
        getMetadtaFieldBuilder() {
      if (metadtaBuilder_ == null) {
        metadtaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dc.raft.network.Metadta, com.dc.raft.network.Metadta.Builder, com.dc.raft.network.MetadtaOrBuilder>(
                getMetadta(),
                getParentForChildren(),
                isClean());
        metadta_ = null;
      }
      return metadtaBuilder_;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes body = 2;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>bytes body = 2;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes body = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Payload)
  }

  // @@protoc_insertion_point(class_scope:Payload)
  private static final com.dc.raft.network.Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dc.raft.network.Payload();
  }

  public static com.dc.raft.network.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payload>
      PARSER = new com.google.protobuf.AbstractParser<Payload>() {
    @java.lang.Override
    public Payload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Payload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Payload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dc.raft.network.Payload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

