// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.dc.raft.network;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadta_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadta_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\032\031google/protobuf/any.pro" +
      "to\"\201\001\n\007Metadta\022\014\n\004type\030\001 \001(\t\022\020\n\010clientIp" +
      "\030\002 \001(\t\022&\n\007headers\030\003 \003(\0132\025.Metadta.Header" +
      "sEntry\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"2\n\007Payload\022\031\n\007metadta\030\001 \001" +
      "(\0132\010.Metadta\022\014\n\004body\030\002 \001(\0142.\n\013RaftReques" +
      "t\022\037\n\007request\022\010.Payload\032\010.Payload\"\0002;\n\016Re" +
      "questStream1\022)\n\rrequestStream\022\010.Payload\032" +
      "\010.Payload\"\000(\0010\001B\027\n\023com.dc.raft.networkP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_Metadta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Metadta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadta_descriptor,
        new java.lang.String[] { "Type", "ClientIp", "Headers", });
    internal_static_Metadta_HeadersEntry_descriptor =
      internal_static_Metadta_descriptor.getNestedTypes().get(0);
    internal_static_Metadta_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadta_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new java.lang.String[] { "Metadta", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
